### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Plastic-Scanner/DB2.x-Firmware#9]
Hello!

I found your project from https://hackaday.io/project/185532-plastic-scanner

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by jurc192** [comment]
Hello,

thanks for pointing it out - I uploaded license information now!. You're welcome to copy, modify and adapt the code (GPLv3 license)
